# Generated by Django 5.0.2 on 2024-03-06 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter_hub', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.IntegerField()),
                ('image_file_name', models.CharField(max_length=255)),
                ('file_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsletter_hub.newsletterdata')),
            ],
        ),
        migrations.CreateModel(
            name='ExtractedText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.IntegerField()),
                ('text_file_name', models.CharField(max_length=255)),
                ('file_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsletter_hub.newsletterdata')),
            ],
        ),
        migrations.CreateModel(
            name='NewsLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_letter_title', models.CharField(max_length=255)),
                ('news_letter_content', models.TextField()),
                ('is_introduction', models.BooleanField(default=False)),
                ('text_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsletter_hub.extractedtext')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(max_length=255)),
                ('article_content', models.TextField()),
                ('article_img', models.ImageField(blank=True, null=True, upload_to='articles/')),
                ('news_letter_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsletter_hub.newsletter')),
            ],
        ),
    ]
