# Generated by Django 5.0.2 on 2024-03-06 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter_hub', '0002_extractedimage_extractedtext_newsletter_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletterdata',
            name='file_name',
            field=models.FileField(upload_to='newsletters/pdfs/'),
        ),
    ]
