# Generated by Django 5.0.2 on 2024-03-07 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter_hub', '0003_alter_newsletterdata_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletterdata',
            name='isGenerated',
            field=models.BooleanField(default=False),
        ),
    ]
