# Generated by Django 5.0.2 on 2024-03-10 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter_hub', '0004_newsletterdata_isgenerated'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='is_closing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='is_content',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='is_greeting',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='is_other',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='is_subject',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='is_wishing',
            field=models.BooleanField(default=False),
        ),
    ]
