# Generated by Django 5.0.2 on 2024-03-10 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter_hub', '0005_newsletter_is_closing_newsletter_is_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsletter',
            name='news_letter_title',
        ),
    ]
