# Generated by Django 5.0.2 on 2024-03-17 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter_hub', '0006_remove_newsletter_news_letter_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsletter',
            name='is_closing',
        ),
        migrations.RemoveField(
            model_name='newsletter',
            name='is_content',
        ),
        migrations.RemoveField(
            model_name='newsletter',
            name='is_greeting',
        ),
        migrations.RemoveField(
            model_name='newsletter',
            name='is_introduction',
        ),
        migrations.RemoveField(
            model_name='newsletter',
            name='is_other',
        ),
        migrations.RemoveField(
            model_name='newsletter',
            name='is_subject',
        ),
        migrations.RemoveField(
            model_name='newsletter',
            name='is_wishing',
        ),
    ]
